[package]
name = "simple_warfare"
version = "0.1.0"
edition = "2024"
exclude = ["assets/"]
resolver = "2"

[workspace]
members = ["crates/simple_warfare_macros"]


[dependencies]
thiserror = "2.0.12"
rand = "0.9.1"
bevy-inspector-egui = "0.31.0"
serde = "1.0.219"
toml = "0.9.2"
mlua = { version = "0.11.1", features = [
    "lua54",
    "async",
    "vendored",
    "anyhow",
    "macros",
    "mlua_derive",
    'serialize',
    "send",
] }
simple_warfare_macros = { path = "crates/simple_warfare_macros" }
oneshot = "0.1.11"
boa_engine = "0.20.0"
boa_runtime = "0.20.0"
boa_gc = "0.20.0"
boa_profiler = "0.20.0"
bevy_ecs_ldtk = { version = "0.12.0", features = ["atlas"] }
rand_core = "0.9.3"
bevy_rand = "0.11"
bevy_prng = { version = "0.11.1", features = ["rand_chacha", "wyrand"] }
bevy_light_2d = "0.6.0"
bevy_fly_camera = "0.16.0"
#bevy-panic-handler = "5.0.0"
avian2d = { version = "0.3.0", features = [
    "2d",
    "f32",
    "parry-f32",
    "parallel",
    "serialize",
] }
bevy_spritesheet_animation = { git = "https://github.com/merwaaan/bevy_spritesheet_animation", features = [
    "custom_cursor",
] }
bevy_tween = "0.9.0"
serde_json = "1.0.140"
rustc-hash = "2.1.1"
url = "2.5.4"
image = "0.25.6"
bevy_polyline = "0.12.0"
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread", "time"] }

vleue_navigator = "0.12.0"
bevy_seedling = { version = "0.4.3", features = ["mp3"] } #audio
bevy_hanabi = { version = "0.16", default-features = false, features = [
    "2d",
    "serde",
] }
bevy_hui = { git = "https://github.com/shishanyue/bevy_hui.git" }
bevy_hui_widgets = "0.3.0"
bevy_spatial = "0.11.0"
bevy_aseprite_ultra = "0.6.1"
fluent = "0.17.0"
bevy_ecs_tiled = { version = "0.7.4", features = ["atlas", "physics"] }
bevy_ecs_tilemap = "0.16.0"
tiled = { version = "0.14.0", features = ["world"] }
parry2d = { version = "0.22.0" }
bevy_quinnet = "0.17.0"
bevy_webgate = "0.1.1"
bevy_web_asset = "0.11.0"
axum = "0.8.4"
bevy_defer = { version = "0.14.0", default-features = false }
pathfinding = "4.14.0"
crc32fast = "1.5.0"
uuid-simd = "0.8.0"
#bevy_window_utils = "0.16.0"
bevy_async_task = "0.8.1"
new_mime_guess = "4.0.4"
[dependencies.bevy]
version = "0.16.1"
features = [
    "bevy_remote",
    "file_watcher",
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_mesh_picking_backend",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    "bevy_window",
    "bevy_winit",
    "custom_cursor",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "webgl2",
    "x11",
    "jpeg",
    "serialize",
]

[dev-dependencies.bevy]
version = "0.16.1"
features = [
    "bevy_remote",
    "file_watcher",
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_mesh_picking_backend",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    "bevy_window",
    "bevy_winit",
    "custom_cursor",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "webgl2",
    "x11",
    "jpeg",
    "dynamic_linking",
]

[profile.release]
opt-level = 3           # 使用稍高一些的优化级别，最低是0，最高是3
overflow-checks = false # 关闭整数溢出检查
codegen-units = 1
lto = "thin"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
