[package]
name = "simple_warfare"
version = "0.1.0"
edition = "2024"
exclude = ["assets/"]


[dependencies]
thiserror = "2.0.12"
rand = "0.9.1"
bevy-inspector-egui = "0.31.0"
serde = "1.0.219"
toml = "0.8.23"
mlua = { version = "0.10.5", features = [
  "lua54",
  "async",
  "vendored",
  "anyhow",
  "macros",
  "mlua_derive",
  'serialize',
  "send",
] }
anyhow = "1.0.82"
boa_engine = "0.20.0"
boa_runtime = "0.20.0"
boa_gc = "0.20.0"
boa_profiler = "0.20.0"
bevy_ecs_ldtk = { version = "0.12.0", features = ["atlas"] }
rand_core = "0.9.3"
bevy_rand = "0.11"
bevy_prng = { version = "0.11.1", features = ["rand_chacha", "wyrand"] }
bevy_light_2d = "0.6.0"
bevy_fly_camera = "0.16.0"
bevy-panic-handler = "5.0.0"
bevy_rapier2d = "0.30.0"
bevy_spritesheet_animation = { git = "https://github.com/merwaaan/bevy_spritesheet_animation", features = [
  "custom_cursor",
] }
bevy_tween = "0.8.0"
serde_json = "1.0.140"
rustc-hash = "2.1.1"
url = "2.5.4"
image = "0.25.6"

[dependencies.bevy]
version = "0.16.1"
features = ["jpeg"]
[dev-dependencies.bevy]
version = "0.16.1"
features = ["jpeg", "dynamic_linking"]

[profile.release]
opt-level = 3           # 使用稍高一些的优化级别，最低是0，最高是3
overflow-checks = false # 关闭整数溢出检查
codegen-units = 1
lto = "thin"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
