[package]
name = "simple_warfare"
version = "0.1.0"
edition = "2024"
exclude = ["assets/"]


[dependencies]
thiserror = "2.0.12"
rand = "0.9.1"
bevy-inspector-egui = "0.31.0"
serde = "1.0.219"
toml = "0.8.23"
tokio = { version = "1.45.1", features = ["full"] }
mlua = { version = "0.10.5", features = [
  "lua54",
  "async",
  "vendored",
  "anyhow",
  "macros",
  "mlua_derive",
  'serialize',
  "send",
] }
anyhow = "1.0.82"
boa_engine = "0.20.0"
boa_runtime = "0.20.0"
boa_gc = "0.20.0"
[dependencies.bevy]
version = "0.16.1"
features = ["jpeg"]
[dev-dependencies.bevy]
version = "0.16.1"
features = ["jpeg", "dynamic_linking"]

[profile.dev]
opt-level = 1           # 使用稍高一些的优化级别，最低是0，最高是3
overflow-checks = false # 关闭整数溢出检查

[profile.release]
opt-level = 3           # 使用稍高一些的优化级别，最低是0，最高是3
overflow-checks = false # 关闭整数溢出检查
codegen-units = 1
lto = "thin"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
