[package]
name = "simple_warfare_shared"
authors.workspace = true
version.workspace = true
edition.workspace = true


[dependencies]
#utils
thiserror.workspace = true

# serialization
serde.workspace = true
toml.workspace = true
serde_json.workspace = true

[dependencies.lightyear]
workspace = true
features = ["server"]

[dependencies.bevy]
workspace = true
default-features = false
