# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
