[package]
name = "simple_warfare_server"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []

[dependencies]
#utils
thiserror.workspace = true
rand.workspace = true
simple_warfare_macros.workspace = true
rand_core = "0.9.3"
bevy_rand = "0.11"
bevy_prng = { version = "0.11.1", features = ["rand_chacha", "wyrand"] }

# serialization
serde.workspace = true
toml.workspace = true
bincode.workspace = true
serde_json.workspace = true

#lua
mlua = { version = "0.11.2", features = [
    "lua54",
    "async",
    "vendored",
    "anyhow",
    "macros",
    "mlua_derive",
    'serialize',
    "send",
] }

#channel
oneshot = "0.1.11"

#boa engine
boa_engine = "0.20.0"
boa_runtime = "0.20.0"
boa_gc = "0.20.0"
boa_profiler = "0.20.0"

#bevy
bevy_light_2d = "0.7.0"
bevy_fly_camera = "0.16.0"
#bevy-panic-handler = "5.0.0"
avian2d = { version = "0.3.0", features = [
    "2d",
    "f32",
    "parry-f32",
    "parallel",
    "serialize",
] }
#bevy_spritesheet_animation = { git = "https://github.com/merwaaan/bevy_spritesheet_animation", features = [
#    "custom_cursor",
#] }

#bevy_trickfilm = "0.11.0"
#bevy_tween = "0.9.0"
rustc-hash = "2.1.1"
url = "2.5.4"
#image = "0.25.6"
#bevy_polyline = "0.12.0"
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread", "time"] }
vleue_navigator2d = { git = "https://github.com/simple-warfare/vleue_navigator2d.git", features = [
    "parry2d",
] }
#bevy_seedling = { version = "0.4.4", features = ["mp3"] } #audio
#bevy_hanabi = { version = "0.16.0", default-features = false, features = [
#    "2d",
#    "serde",
#] }

#bevy_hui = { git = "https://github.com/shishanyue/bevy_hui.git" }
#bevy_hui_widgets = "0.3.0"
bevy_spatial = "0.11.0"
#bevy_aseprite_ultra = "0.6.1"
fluent = "0.17.0"
bevy_ecs_tiled = { version = "0.8.0", default-features = false, features = [
    "atlas",
    "physics",
] }
bevy_ecs_tilemap = { version = "0.16.0", default-features = false }
tiled = { version = "0.14.0", features = ["world"] }
parry2d = { version = "0.23.0" }
bevy_quinnet = "0.17.0"
bevy_webgate = "0.1.1"

#bevy_web_asset = "0.11.0"
axum = "0.8.4"

bevy_defer = { version = "0.14.0", default-features = false }

pathfinding = "4.14.0"
crc32fast = "1.5.0"
uuid-simd = "0.8.0"
#bevy_window_utils = "0.16.0"
bevy_async_task = "0.8.1"
new_mime_guess = "4.0.4"

bevy_northstar = { git = "https://github.com/simple-warfare/bevy_northstar.git", features = [
    "serde",
] }
#bevy_enhanced_input = "0.16.0"
indexmap = "2.10.0"

rayon = "1.10.0"
dashmap = { version = "6.1.0", features = ["rayon"] }


[dependencies.lightyear]
version = "0.23.0"
features = [
    "netcode",
    "steam",
    "udp",
    "webtransport",
    "input_bei",
    "deterministic",
]

[dependencies.bevy]
version = "0.16.1"
default-features = false
features = [
    "std",
    "bevy_log",
    "async_executor",
    "bevy_remote",
    "file_watcher",
    "bevy_asset",
    "bevy_state",
    "multi_threaded",
    "sysinfo_plugin",
    "serialize",
]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
